### ISSUE TITLE
Analyzer shows a white page for a simple profile

### ISSUE THREAD

**Issue by ulfjack** [EngFlow/bazel_invocation_analyzer#99]
## Description

Analyzer shows a white page for a simple profile

### Observed behavior

Analyzer shows a white page for a simple profile

### Expected behavior

Show a list of suggestions.

### Step-by-step guide on how to reproduce the bug

Upload a profile.

## Additional context

...

### Environment

- Browser: Chrome
- Operating System: Linux
- Other:

### Output

```
main.js:8 Error: Could not find item with key 99d73fec-6d20-4322-aacc-02d3c2b31cfd in local storage.
    at Jwt (main.js:22:176696)
    at main.js:37:164836
    at Rx (main.js:8:24501)
    at Wp (main.js:8:43140)
    at main.js:8:41441
    at iU (main.js:1:30857)
    at MessagePort.tU (main.js:1:31257)
main.js:22 Uncaught Error: Could not find item with key 99d73fec-6d20-4322-aacc-02d3c2b31cfd in local storage.
    at Jwt (main.js:22:176696)
    at main.js:37:164836
    at Rx (main.js:8:24501)
    at Wp (main.js:8:43140)
    at main.js:8:41441
    at iU (main.js:1:30857)
    at MessagePort.tU (main.js:1:31257)
```

### File(s) scanned

Optionally provide file(s) that demonstrate the bug when running the tool.

Ideally, do not attach files directly. Bazel profiles can include sensitive data, such as exposing
which dependencies your project includes.

Instead, upload files to the cloud storage provider of your choice and grant appropriate access.
This allows you to adjust who can access them now and in the future. For example, you may want to
remove access to the files once the issue has been resolved.

### Further details

Provide other data related to this issue that may prove helpful.

**Comment by ulfjack** [comment]
@saraadams

**Comment by saraadams** [comment]
I found two issues and have fixes for them.
White page: this is caused by an uncaught error.
Cause of white page: This looks to be a race condition in play, which is why reloading the "white page" may show the results.
The fixes will be part of the next release.

If you encounter this bug before the new release has been rolled out, try refreshing the white page whenever you encounter it on analyzing a profile. It looks like the race condition is at least much rarer (or plays out in our favor) when you reload the page.

**Comment by saraadams** [comment]
This is now rolled out and was confirmed as fixed by the initial reporter.
